springer_journals = [
        'APMIS',
        'Acad Emerg Med',
        'Acta Anaesthesiol Scand',
        'Acta Crystallogr C',
        'Acta Neurol Scand Supplc',
        'Acta Neuropathol',
        'Acta Neuropsychiatr',
        'Acta Obstet Gynecol Scand',
        'Acta Obstet Gynecol Scand Suppl',
        'Acta Ophthalmol',
        'Acta Ophthalmol Scand Suppl',
        'Acta Paediatr Jpn',
        'Acta Paediatr Suppl',
        'Acta Pathol Jpn',
        'Acta Pathol Microbiol Scand B',
        'Acta Physiol (Oxf)',
        'Acta Physiol Scand',
        'Acta Psychiatr Scand',
        'Addict Biol',
        'Addiction',
        'Adv Exp Med Biol',
        'Aging Cell',
        'Alcohol Clin Exp Res',
        'Aliment Pharmacol Ther',
        'Am J Addict',
        'Am J Anat',
        'Am J Hum Biol',
        'Am J Ind Med',
        'Am J Med Genet C Semin Med Genet',
        'Am J Phys Anthropol',
        'Am J Primatol',
        'Am J Reprod Immunol',
        'Am J Transplant',
        'Anaesthesia',
        'Anat Histol Embryol',
        'Anat Rec',
        'Anat Rec (Hoboken)',
        'Andrology',
        'Angew Chem Int Ed Engl',
        'Anim Sci J',
        'Ann Endocrinol (Paris)',
        'Ann Hematol',
        'Ann N Y Acad Sci',
        'Ann Noninvasive Electrocardiol',
        'Ann Surg Oncol',
        'Antivir Ther (Lond)',
        'Arch Dermatol Res',
        'Arch Insect Biochem Physiol',
        'Arch Pharm (Weinheim)',
        'Arch Virol',
        'Arthritis & rheumatology (Hoboken NJ)',
        'Arthritis Care Res (Hoboken)',
        'Artif Organs',
        'Asia Pac J Clin Oncol',
        'Asia Pac Psychiatry',
        'Aust Dent J',
        'Aust N Z J Obstet Gynaecol',
        'Aust Vet J',
        'Autism Res',
        'BJOG',
        'Biochem Genet',
        'Biochem Mol Biol Educ',
        'Biochem Mol Biol Int',
        'Biochemistry Mosc',
        'Bioelectromagnetics',
        'Bioessays',
        'Biofactors',
        'Biol Cell',
        'Biol Rev Camb Philos Soc',
        'Biom J',
        'Biomed Biochim Acta',
        'Biomed Chromatogr',
        'Bioorg Med Chem Lett',
        'Biopharm Drug Dispos',
        'Biotechnol Appl Biochem',
        'Biotechnol J',
        'Biotechnol Lett',
        'Biotechnol Prog',
        'Bipolar Disord',
        'Birth Defects Res C Embryo Today',
        'Birth Defects Res Part A Clin Mol Teratol',
        'Br J Surg',
        'Brain Pathol',
        'Breast Cancer Res Treat',
        'CNS Neurosci Ther',
        'Calcif Tissue Int',
        'Cancer Chemother Pharmacol',
        'Cancer Cytopathol',
        'Cancer Med',
        'Cardiovasc Drug Rev',
        'Cardiovasc Ther',
        'Cathet Cardiovasc Diagn',
        'Catheter Cardiovasc Interv',
        'Cell Biochem Funct',
        'Cell Biol Int',
        'Cell Microbiol',
        'Cell Mol Biol (Noisy-le-grand)',
        'Cell Mol Neurobiol',
        'Cell Motil Cytoskeleton',
        'Cell Prolif',
        'Cell Tissue Kinet',
        'Chem Asian J',
        'Chem Biodivers',
        'Chem Biol Drug Des',
        'Chem Pharm Bull',
        'Chem Rec',
        'ChemMedChem',
        'ChemSusChem',
        'Chemphyschem',
        'Child Dev',
        'Chirality',
        'Clin Cardiol',
        'Clin Exp Pharmacol Physiol',
        'Clin Exp Pharmacol Physiol Suppl',
        'Clin Experiment Ophthalmol',
        'Clin Lab Haematol',
        'Clin Oral Implants Res',
        'Clin Otolaryngol Allied Sci',
        'Clin Physiol',
        'Clin Physiol Funct Imaging',
        'Clin Respir J',
        'Clin Transl Sci',
        'Clin Transplant',
        'Cochrane Database Syst Rev',
        'Colorectal Dis',
        'Congenit Anom (Kyoto)',
        'Congest Heart Fail',
        'Contact Derm',
        'Contrast Media Mol Imaging',
        'Cytometry',
        'Cytometry A',
        'Cytopathology',
        'Depress Anxiety',
        'Dermatol Ther',
        'Dev Genet',
        'Dev Growth Differ',
        'Dev Neurobiol',
        'Diabetes Metab Res Rev',
        'Diabetes Obes Metab',
        'Diabetologia',
        'Diagn Cytopathol',
        'Differentiation',
        'Dig Dis Sci',
        'Dig Endosc',
        'Dis Esophagus',
        'Drug Test Anal',
        'EDTNA ERCA J',
        'Emerg Med Australas',
        'Endocrine',
        'Endod Dent Traumatol',
        'Environ Microbiol',
        'Environ Microbiol Rep',
        'Environ Mutagen',
        'Environ Toxicol',
        'Environ Toxicol Chem',
        'Equine Vet J',
        'Equine Vet J Suppl',
        'Eur Eat Disord Rev',
        'Eur J Clin Pharmacol',
        'Eur J Dermatol',
        'Eur J Haematol Suppl',
        'Eur J Heart Fail',
        'Eur J Immunol',
        'Eur J Nutr',
        'Eur J Oral Sci',
        'Eur J Pain',
        'Eur J Pediatr',
        'Evolution',
        'Exp Physiol',
        'Fam Cancer',
        'Farmaco',
        'Fundam Clin Pharmacol',
        'Genesis',
        'Geobiology',
        'Geriatr Gerontol Int',
        'Glia',
        'Graefes Arch Clin Exp Ophthalmol',
        'HNO',
        'Helicobacter',
        'Hematol Oncol',
        'Hemodial Int',
        'Hereditas',
        'Hippocampus',
        'Histopathology',
        'Hum Genet',
        'Hum Psychopharmacol',
        'IUBMB Life',
        'Immunogenetics',
        'Influenza Other Respir Viruses',
        'Insect Mol Biol',
        'Insect Sci',
        'Int Arch Allergy Appl Immunol',
        'Int Endod J',
        'Int Forum Allergy Rhinol',
        'Int J Colorectal Dis',
        'Int J Eat Disord',
        'Int J Geriatr Psychiatry',
        'Int J Gynecol Cancer',
        'Int J Hematol',
        'Int J Lang Commun Disord',
        'Int J Paediatr Dent',
        'Int J Rheum Dis',
        'Int J Stroke',
        'Int J Urol',
        'Intern Med J',
        'J Am Geriatr Soc',
        'J Anat',
        'J Androl',
        'J Anim Breed Genet',
        'J Appl Genet',
        'J Appl Microbiol',
        'J Appl Toxicol',
        'J Basic Microbiol',
        'J Biochem Mol Toxicol',
        'J Biol Inorg Chem',
        'J Biolumin Chemilumin',
        'J Biomed Mater Res',
        'J Biomed Mater Res A',
        'J Biomed Mater Res Part B Appl Biomater',
        'J Biomol NMR',
        'J Bone Miner Metab',
        'J Cancer Res Clin Oncol',
        'J Cardiometab Syndr',
        'J Cardiovasc Electrophysiol',
        'J Cell Biochem Suppl',
        'J Cell Mol Med',
        'J Child Psychol Psychiatry',
        'J Clin Hypertens (Greenwich)',
        'J Clin Immunol',
        'J Clin Periodontol',
        'J Clin Pharm Ther',
        'J Clin Pharmacol',
        'J Clin Psychol',
        'J Comp Neurol',
        'J Comput Chem',
        'J Cutan Pathol',
        'J Diabetes',
        'J Dig Dis',
        'J Dtsch Dermatol Ges',
        'J Endocrinol Invest',
        'J Evid Based Med',
        'J Exp Anal Behav',
        'J Exp Zool',
        'J Exp Zool B Mol Dev Evol',
        'J Exp Zoolog Part A Comp Exp Biol',
        'J Fish Biol',
        'J Food Sci',
        'J Forensic Sci',
        'J Formos Med Assoc',
        'J Gene Med',
        'J Hum Nutr Diet',
        'J Immunogenet',
        'J Inherit Metab Dis',
        'J Integr Plant Biol',
        'J Intellect Disabil Res',
        'J Lab Clin Med',
        'J Magn Reson Imaging',
        'J Mass Spectrom',
        'J Matern Fetal Med',
        'J Med Primatol',
        'J Microsc',
        'J Mol Evol',
        'J Mol Med',
        'J Mol Med (Berl)',
        'J Mol Model',
        'J Mol Neurosci',
        'J Mol Recognit',
        'J Neural Transm',
        'J Neurobiol',
        'J Neuroendocrinol',
        'J Neurol',
        'J Neurooncol',
        'J Obstet Gynaecol Res',
        'J Oral Pathol Med',
        'J Org Chem',
        'J Paediatr Child Health',
        'J Pept Res',
        'J Periodont Res',
        'J Peripher Nerv Syst',
        'J Pharm Pharmacol',
        'J Pharm Sci',
        'J Pineal Res',
        'J Prosthodont',
        'J Sci Food Agric',
        'J Sep Sci',
        'J Sex Med',
        'J Sleep Res',
        'J Small Anim Pract',
        'J Surg Oncol',
        'J Tissue Eng Regen Med',
        'J Vet Emerg Crit Care (San Antonio)',
        'J Vet Intern Med',
        'J Vet Med A Physiol Pathol Clin Med',
        'J Vet Pharmacol Ther',
        'Jpn J Cancer Res',
        'Laryngoscope',
        'Lasers Surg Med',
        'Lett Appl Microbiol',
        'Liver',
        'Liver Transpl',
        'Macromol Rapid Commun',
        'Magn Reson Chem',
        'Magn Reson Med',
        'Matern Child Health J',
        'Med Oncol',
        'Med Pediatr Oncol',
        'Med Res Rev',
        'Med Vet Entomol',
        'Ment Retard Dev Disabil Res Rev',
        'Methods Mol Biol',
        'Microbiol Immunol',
        'Microcirculation',
        'Microsc Res Tech',
        'Mikrobiyol Bul',
        'Mod Rheumatol',
        'Mol Biol Rep',
        'Mol Cell Biochem',
        'Mol Ecol',
        'Mol Genet Genomics',
        'Mol Nutr Food Res',
        'Mol Oral Microbiol',
        'Mol Reprod Dev',
        'Mt Sinai J Med',
        'Muscle Nerve Suppl',
        'Mycoses',
        'NMR Biomed',
        'Nat Toxins',
        'Nephrology (Carlton)',
        'Neurochem Res',
        'Neurogenetics',
        'Neurol Sci',
        'Neuropathology',
        'Neurourol Urodyn',
        'New Phytol',
        'Novartis Found Symp',
        'Nutr Clin Care',
        'Obes Res',
        'Obes Rev',
        'Ophthalmic Physiol Opt',
        'Ophthalmologe',
        'Opt Express',
        'Oral Dis',
        'Oral Microbiol Immunol',
        'Orthod Craniofac Res',
        'Orthop Surg',
        'Osteoporos Int',
        'Otolaryngol Head Neck Surg',
        'Paediatr Perinat Epidemiol',
        'Pathol Int',
        'Pediatr Dermatol',
        'Pediatr Nephrol',
        'Pediatr Obes',
        'Pflugers Arch',
        'Pharm Res',
        'Pharmacoepidemiol Drug Saf',
        'Pharmacol Toxicol',
        'Pharmacotherapy',
        'Photodermatol Photoimmunol Photomed',
        'Physiol Plant',
        'Phytother Res',
        'Pigment Cell Melanoma Res',
        'Pigment Cell Res',
        'Plant Biol (Stuttg)',
        'Plant Biotechnol J',
        'Plant Cell Rep',
        'Protein Cell',
        'Proteomics',
        'Proteomics Clin Appl',
        'Psychiatry Clin Neurosci',
        'Psychogeriatrics',
        'Psychophysiology',
        'Public Health Nurs',
        'Rapid Commun Mass Spectrom',
        'Recenti Prog Med',
        'Reprod Domest Anim',
        'Respirology',
        'Rheumatol Int',
        'Scand J Haematol',
        'Scand J Med Sci Sports',
        'Schizophr Res',
        'Skin Res Technol',
        'Small',
        'Stat Med',
        'Stem Cells',
        'Synapse',
        'Teratog Carcinog Mutagen',
        'Ther Apher Dial',
        'Transbound Emerg Dis',
        'Transpl Infect Dis',
        'Transpl Int',
        'Trop Med Int Health',
        'Tumour Biol',
        'Ugeskr Laeg',
        'Ultrasound Obstet Gynecol',
        'Vet Anaesth Analg',
        'Vet Clin Pathol',
        'Vet Dermatol',
        'Vet Ophthalmol',
        'Vet Surg',
        'Virchows Arch',
        'Virus Genes',
        'Wiley Interdiscip Rev RNA',
        'World J Surg',
        'Xenotransplantation',
        'Yakugaku Zasshi',
        'Yi Chuan Xue Bao',
        'Z Allg Mikrobiol',
        'Z Tierpsychol',
        'Zentralbl Veterinarmed A',
        'Zh Nevrol Psikhiatr Im S S Korsakova',
        'Zhongguo Shi Yan Xue Ye Xue Za Zhi',
        'Zhonghua Bing Li Xue Za Zhi',
        'Zhonghua Er Ke Za Zhi',
        'Zhonghua Kou Qiang Yi Xue Za Zhi',
        'Zhonghua Yan Ke Za Zhi',
        'Zoonoses Public Health',
]